language: cpp
compiler: gcc
python:
  - "2.6"
  - "2.7"
before_install:
  sudo pip install gcovr
  
env:
  - NUM_MOVES=1
  - NUM_MOVES=10
  - NUM_MOVES=100
  - NUM_MOVES=1000
  
script:
  - make compile
  - make test
  - make coverage-xml
  
branches:
  only:
    - master

notifications:
  email:
    recipients:
      - x3mSpeedy@gmail.com
    on_success: change
    on_failure: always
