language: cpp
compiler: gcc
python:
  - "2.6"
  - "2.7"
before_install:
  - sudo pip install gcovr
  - sudo pip install cpp-coveralls
  
env:
  - NUM_MOVES=9000000 MOVES_SEED=80

  
script:
  - make compile
  - make test
#  - make coverage-xml
#  - wc -l output.txt
#  - tail -n 30 output.txt
  
after_success:
  coveralls -t 0fEMMjXW6NdIqEBZTU0xGYBGTnSCupqKo
  
branches:
  only:
    - master

notifications:
  email:
    recipients:
      - x3mSpeedy@gmail.com
    on_success: change
    on_failure: always
